CI/CD: check exit code of docker

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -42,3 +42,12 @@ jobs:
         run: |
           npm run test-docker
 
+      - name: Check Jest exit code
+        run: |
+          if [ $? -ne 0 ]; then
+            echo "Jest tests failed"
+            exit 1
+          else
+            echo "Jest tests passed"
+          fi
+
diff --git a/.github/workflows/google-cloudrun-docker.yml b/.github/workflows/google-cloudrun-docker.yml
--- a/.github/workflows/google-cloudrun-docker.yml
+++ b/.github/workflows/google-cloudrun-docker.yml
@@ -76,6 +76,16 @@ jobs:
       - name: Build and test Docker image
         run: |
           npm run test-docker
+
+      - name: Check Jest exit code
+        run: |
+          if [ $? -ne 0 ]; then
+            echo "Jest tests failed"
+            exit 1
+          else
+            echo "Jest tests passed"
+          fi
+        
   deploy:
 
     needs: test
